name: Add pull requests to project board

on:
  pull_request:
    types:
      - labeled
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/cadamini/projects/1
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          labeled: bug 
